# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_displayed', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('priority',),
                'abstract': False,
            },
        ),
    ]
