# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='file',
            field=models.FileField(blank=True, help_text='Audio file', null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, help_text='Image (gif/jpg/png)', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='text',
            field=models.TextField(blank=True, help_text='Text of podcast', null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(help_text='Name of podcast', max_length=250),
        ),
    ]
